# -*- coding: utf-8 -*-

# The MIT License (MIT) - Copyright (c) Dave Vandenbout.

"""
Post-process a KiCad 8/9 schematic (.kicad_sch) generated by SKiDL to add
global net labels at each pin position.

SKiDL's ``generate_schematic()`` produces hierarchical schematics with
correct symbols and netlists, but without visible net labels on the pins.
This module reads the companion ``.net`` netlist, resolves pin-to-net
mappings, and injects ``(global_label ...)`` S-expressions at the world
coordinates of every connected pin.

Features:
  - Parses KiCad S-expression schematics and netlists (no external deps)
  - Handles symbol rotation, mirror, and multi-unit sub-symbols
  - Deduplicates labels at identical positions (e.g. stacked USB-C GND pins)
  - Orients labels to point away from the symbol body
  - Converts auto-generated net names (``N$1``, ``Net-(R1-1)``) to readable form

Usage as CLI::

    python -m skidl.tools.inject_labels schematic.kicad_sch netlist.net output.kicad_sch

Usage from Python::

    from skidl.tools.inject_labels import inject_labels
    inject_labels("power1.kicad_sch", "circuit.net", "power1_labeled.kicad_sch")
"""

from __future__ import annotations

import math
import sys
import uuid
from typing import Any


# ---------------------------------------------------------------------------
# S-expression parser  (recursive descent, no external deps)
# ---------------------------------------------------------------------------

def parse_sexp(text: str) -> list:
    """Parse a KiCad S-expression string into nested Python lists.

    Atoms are kept as strings.  Quoted strings have their quotes stripped.
    Numbers are NOT converted -- everything stays as ``str`` so we can
    round-trip without floating-point surprises.
    """
    tokens = _tokenize(text)
    result, _ = _parse_tokens(tokens, 0)
    return result


def _tokenize(text: str) -> list[str]:
    """Split *text* into a flat list of tokens: ``(``, ``)``, quoted strings,
    and bare atoms."""
    tokens: list[str] = []
    i = 0
    n = len(text)
    while i < n:
        ch = text[i]
        if ch in " \t\n\r":
            i += 1
        elif ch == "(":
            tokens.append("(")
            i += 1
        elif ch == ")":
            tokens.append(")")
            i += 1
        elif ch == '"':
            # Quoted string -- find matching close quote, handling \"
            j = i + 1
            while j < n:
                if text[j] == "\\" and j + 1 < n:
                    j += 2
                elif text[j] == '"':
                    break
                else:
                    j += 1
            tokens.append(text[i + 1 : j])  # strip quotes
            i = j + 1
        else:
            # Bare atom (number, keyword, etc.)
            j = i
            while j < n and text[j] not in " \t\n\r()\"":
                j += 1
            tokens.append(text[i:j])
            i = j
    return tokens


def _parse_tokens(tokens: list[str], pos: int) -> tuple[Any, int]:
    """Recursively parse tokens starting at *pos*.
    Returns ``(parsed_value, next_pos)``.
    """
    if tokens[pos] == "(":
        lst: list = []
        pos += 1  # skip '('
        while pos < len(tokens) and tokens[pos] != ")":
            val, pos = _parse_tokens(tokens, pos)
            lst.append(val)
        pos += 1  # skip ')'
        return lst, pos
    else:
        return tokens[pos], pos + 1


# ---------------------------------------------------------------------------
# Netlist (.net) parser
# ---------------------------------------------------------------------------

def parse_netlist(path: str) -> dict[tuple[str, str], str]:
    """Return a mapping of ``(component_ref, pin_number) -> net_name``
    from a KiCad .net netlist file.
    """
    with open(path, "r") as f:
        tree = parse_sexp(f.read())

    pin_to_net: dict[tuple[str, str], str] = {}

    nets_sections = _find_all(tree, "nets")
    if not nets_sections:
        return pin_to_net

    nets_section = nets_sections[0]
    for net in _find_all(nets_section, "net"):
        net_name = _get_value(net, "name")
        if net_name is None:
            continue
        for node in _find_all(net, "node"):
            ref = _get_value(node, "ref")
            pin = _get_value(node, "pin")
            if ref is not None and pin is not None:
                pin_to_net[(ref, pin)] = net_name

    return pin_to_net


# ---------------------------------------------------------------------------
# Schematic parser helpers
# ---------------------------------------------------------------------------

def _find(sexp: list, tag: str) -> list | None:
    """Find the first child list whose first element equals *tag*."""
    for item in sexp:
        if isinstance(item, list) and item and item[0] == tag:
            return item
    return None


def _find_all(sexp: list, tag: str) -> list:
    """Return all child lists whose first element equals *tag*."""
    return [item for item in sexp
            if isinstance(item, list) and item and item[0] == tag]


def _get_value(sexp: list, tag: str) -> str | None:
    """Get the string value of a ``(tag value)`` child, or ``None``."""
    node = _find(sexp, tag)
    if node and len(node) >= 2 and isinstance(node[1], str):
        return node[1]
    return None


# ---------------------------------------------------------------------------
# Extract lib_symbol pin definitions
# ---------------------------------------------------------------------------

def extract_lib_pins(tree: list) -> dict[str, list[dict]]:
    """Parse the ``lib_symbols`` section of the schematic.

    Returns ``{lib_id: [pin_dict, ...]}`` where each *pin_dict* has keys:
    ``number``, ``name``, ``x``, ``y``, ``angle``.

    Pins live in sub-symbols named ``SYMBOLNAME_N_1`` (unit sub-symbols).
    We collect pins from all unit sub-symbols.
    """
    lib_syms_node = _find(tree, "lib_symbols")
    if lib_syms_node is None:
        return {}

    result: dict[str, list[dict]] = {}
    for sym in _find_all(lib_syms_node, "symbol"):
        lib_id = sym[1]
        pins: list[dict] = []
        _collect_pins(sym, pins)
        result[lib_id] = pins

    return result


def _collect_pins(node: list, pins: list[dict]) -> None:
    """Recursively collect pin defs from a lib_symbol or its sub-symbols."""
    for child in node:
        if not isinstance(child, list) or not child:
            continue
        if child[0] == "pin":
            pin_info = _parse_pin(child)
            if pin_info:
                pins.append(pin_info)
        elif child[0] == "symbol":
            _collect_pins(child, pins)


def _parse_pin(pin_sexp: list) -> dict | None:
    """Parse a ``(pin TYPE STYLE (at X Y ANGLE) ... (name ...) (number ...))``."""
    at_node = _find(pin_sexp, "at")
    num_node = _find(pin_sexp, "number")
    name_node = _find(pin_sexp, "name")

    if at_node is None or num_node is None:
        return None

    return {
        "number": num_node[1] if len(num_node) >= 2 else "",
        "name": name_node[1] if name_node and len(name_node) >= 2 else "",
        "x": float(at_node[1]),
        "y": float(at_node[2]),
        "angle": float(at_node[3]) if len(at_node) > 3 else 0.0,
    }


# ---------------------------------------------------------------------------
# Extract symbol instances from the schematic
# ---------------------------------------------------------------------------

def extract_instances(tree: list) -> list[dict]:
    """Extract all ``(symbol (lib_id ...) (at SX SY SROT) ...)`` instances.

    Returns a list of dicts with keys: ``lib_id``, ``ref``, ``sx``, ``sy``,
    ``rotation``, ``mirror_x``, ``mirror_y``.
    """
    instances = []
    for node in tree:
        if not isinstance(node, list) or not node:
            continue
        if node[0] != "symbol":
            continue
        lib_id_node = _find(node, "lib_id")
        if lib_id_node is None:
            continue

        at_node = _find(node, "at")
        if at_node is None:
            continue

        sx = float(at_node[1])
        sy = float(at_node[2])
        rotation = float(at_node[3]) if len(at_node) > 3 else 0.0

        ref = None
        for prop in _find_all(node, "property"):
            if len(prop) >= 3 and prop[1] == "Reference":
                ref = prop[2]
                break

        mirror_node = _find(node, "mirror")
        mirror_x = mirror_y = False
        if mirror_node and len(mirror_node) >= 2:
            mirror_x = "x" in mirror_node[1]
            mirror_y = "y" in mirror_node[1]

        if ref is None:
            continue

        instances.append({
            "lib_id": lib_id,
            "ref": ref,
            "sx": sx, "sy": sy,
            "rotation": rotation,
            "mirror_x": mirror_x, "mirror_y": mirror_y,
        })

    return instances


# ---------------------------------------------------------------------------
# Coordinate transform: pin local -> world
# ---------------------------------------------------------------------------

def pin_world_pos(
    sx: float, sy: float, rotation: float,
    mirror_x: bool, mirror_y: bool,
    px: float, py: float,
) -> tuple[float, float]:
    """Transform a pin's local offset to world coordinates.

    Accounts for symbol placement, rotation (degrees), and mirror flags.
    KiCad Y-down coordinate system: positive rotation is clockwise.
    """
    if mirror_x:
        py = -py
    if mirror_y:
        px = -px

    rad = math.radians(rotation)
    cos_r = math.cos(rad)
    sin_r = math.sin(rad)

    return (
        sx + px * cos_r - py * sin_r,
        sy + px * sin_r + py * cos_r,
    )


def label_angle_from_position(
    sx: float, sy: float, wx: float, wy: float,
) -> float:
    """Compute label angle so it extends AWAY from the symbol body.

    Returns one of 0, 90, 180, 270 (KiCad label angle convention).
    """
    dx = wx - sx
    dy = wy - sy

    if abs(dx) < 0.01 and abs(dy) < 0.01:
        return 0.0

    angle_rad = math.atan2(-dy, dx)  # negate dy for Y-down → Y-up
    angle_deg = math.degrees(angle_rad) % 360
    return float(round(angle_deg / 90) * 90 % 360)


# ---------------------------------------------------------------------------
# Net name utilities
# ---------------------------------------------------------------------------

def is_unnamed_net(name: str) -> bool:
    """Return True if the net name looks auto-generated / unnamed."""
    return name.startswith("N$") or name.startswith("Net-")


def readable_net_name(name: str) -> str:
    """Convert an auto-generated net name to something readable.

    ``N$1`` → ``net1``, ``Net-(R1-1)`` → ``R1_1``.
    """
    if name.startswith("N$"):
        return f"net{name[2:]}"
    if name.startswith("Net-"):
        inner = name[4:].strip("()")
        return inner.replace("-", "_")
    return name


# ---------------------------------------------------------------------------
# Label S-expression generation
# ---------------------------------------------------------------------------

def _fmt(val: float) -> str:
    """Format a float, dropping unnecessary trailing zeros."""
    if val == int(val):
        return str(int(val))
    return f"{val:.4f}".rstrip("0").rstrip(".")


def make_global_label_sexp(
    net_name: str, x: float, y: float, angle: float,
) -> str:
    """Return a KiCad 8/9 ``(global_label ...)`` S-expression string."""
    uid = str(uuid.uuid4())
    return (
        f'  (global_label "{net_name}"\n'
        f"    (shape input)\n"
        f"    (at {_fmt(x)} {_fmt(y)} {_fmt(angle)})\n"
        f"    (effects\n"
        f"      (font\n"
        f"        (size 1.27 1.27)))\n"
        f'    (uuid "{uid}"))\n'
    )


# ---------------------------------------------------------------------------
# Main pipeline
# ---------------------------------------------------------------------------

def inject_labels(sch_path: str, net_path: str, out_path: str) -> int:
    """Read schematic + netlist, inject global labels at pin positions.

    Args:
        sch_path: Path to a ``.kicad_sch`` file (input).
        net_path: Path to a ``.net`` netlist file.
        out_path: Path for the labeled ``.kicad_sch`` file (output).

    Returns:
        Number of labels injected.
    """
    with open(sch_path, "r") as f:
        sch_text = f.read()

    tree = parse_sexp(sch_text)
    pin_to_net = parse_netlist(net_path)
    lib_pins = extract_lib_pins(tree)
    instances = extract_instances(tree)

    labels_to_add: list[str] = []
    placed: set[tuple[str, int, int]] = set()  # (net_name, qx, qy)

    for inst in instances:
        pins = lib_pins.get(inst["lib_id"], [])
        for pin in pins:
            net_name = pin_to_net.get((inst["ref"], pin["number"]))
            if net_name is None:
                continue
            if is_unnamed_net(net_name):
                net_name = readable_net_name(net_name)

            wx, wy = pin_world_pos(
                inst["sx"], inst["sy"], inst["rotation"],
                inst["mirror_x"], inst["mirror_y"],
                pin["x"], pin["y"],
            )
            la = label_angle_from_position(inst["sx"], inst["sy"], wx, wy)

            key = (net_name, round(wx * 100), round(wy * 100))
            if key in placed:
                continue
            placed.add(key)

            labels_to_add.append(make_global_label_sexp(net_name, wx, wy, la))

    # Insert labels just before the final closing ')' of the file.
    rpos = sch_text.rfind(")")
    if rpos == -1:
        print("ERROR: could not find closing ')' in schematic", file=sys.stderr)
        return 0

    new_text = sch_text[:rpos] + "\n" + "".join(labels_to_add) + sch_text[rpos:]
    with open(out_path, "w") as f:
        f.write(new_text)

    print(f"Injected {len(labels_to_add)} labels into {out_path}")
    return len(labels_to_add)


# ---------------------------------------------------------------------------
# CLI entry point
# ---------------------------------------------------------------------------

def main() -> None:
    if len(sys.argv) != 4:
        print(
            "Usage: python -m skidl.tools.inject_labels "
            "<schematic.kicad_sch> <netlist.net> <output.kicad_sch>",
            file=sys.stderr,
        )
        sys.exit(1)

    inject_labels(sys.argv[1], sys.argv[2], sys.argv[3])


if __name__ == "__main__":
    main()
